version: '3'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - cms-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
